"""Adicionando colunas race e character_class

Revision ID: 83a79dfdf852
Revises: 22505e0851e9
Create Date: 2025-03-19 22:10:47.729408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a79dfdf852'
down_revision: Union[str, None] = '22505e0851e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('race', sa.Enum('HUMAN', 'ELF', 'DWARF', 'HALFLING', 'DRAGONBORN', 'TIEFLING', 'HALF_ORC', name='raceenum'), nullable=True))
    op.add_column('characters', sa.Column('character_class', sa.Enum('WARRIOR', 'MAGE', 'CLERIC', 'ROGUE', 'PALADIN', 'RANGER', 'BARD', name='characterclassenum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
